package com.metodi.workforcemanagement.test_resources;

public interface CalendarServiceTestJSON {
    String HOLIDAYS_API_MOCK_RESULT = "{\"meta\":{\"code\":200},\"response\":{\"holidays\":[\n" +
            "{\"name\":\"Labor Day\",\"description\":\"May Day, or Labor Day, is a day off for workers in many countries around the world.\",\"country\":{\"id\":\"bg\",\"name\":\"Bulgaria\"},\"date\":{\"iso\":\"2020-05-01\",\"datetime\":{\"year\":2020,\"month\":5,\"day\":1}},\"type\":[\"National holiday\"],\"locations\":\"All\",\"states\":\"All\"},\n" +
            "{\"name\":\"St. George's Day\",\"description\":\"St. George's Day is a national holiday in Bulgaria\",\"country\":{\"id\":\"bg\",\"name\":\"Bulgaria\"},\"date\":{\"iso\":\"2020-05-06\",\"datetime\":{\"year\":2020,\"month\":5,\"day\":6}},\"type\":[\"National holiday\"],\"locations\":\"All\",\"states\":\"All\"},\n" +
            "{\"name\":\"St. George's Day\",\"description\":\"St. George's Day is a national holiday in Bulgaria\",\"country\":{\"id\":\"bg\",\"name\":\"Bulgaria\"},\"date\":{\"iso\":\"2020-05-06\",\"datetime\":{\"year\":2020,\"month\":5,\"day\":6}},\"type\":[\"National holiday\"],\"locations\":\"All\",\"states\":\"All\"},\n" +
            "{\"name\":\"Culture and Literacy Day\",\"description\":\"Culture and Literacy Day is a national holiday in Bulgaria\",\"country\":{\"id\":\"bg\",\"name\":\"Bulgaria\"},\"date\":{\"iso\":\"2020-05-24\",\"datetime\":{\"year\":2020,\"month\":5,\"day\":24}},\"type\":[\"National holiday\"],\"locations\":\"All\",\"states\":\"All\"},\n" +
            "{\"name\":\"Culture and Literacy Day observed\",\"description\":\"Culture and Literacy Day is a national holiday in Bulgaria\",\"country\":{\"id\":\"bg\",\"name\":\"Bulgaria\"},\"date\":{\"iso\":\"2020-05-25\",\"datetime\":{\"year\":2020,\"month\":5,\"day\":25}},\"type\":[\"National holiday\"],\"locations\":\"All\",\"states\":\"All\"},\n" +
            "{\"name\":\"June Solstice\",\"description\":\"June Solstice in Bulgaria (Sofia)\",\"country\":{\"id\":\"bg\",\"name\":\"Bulgaria\"},\"date\":{\"iso\":\"2020-06-21T00:43:40+03:00\",\"datetime\":{\"year\":2020,\"month\":6,\"day\":21,\"hour\":0,\"minute\":43,\"second\":40},\"timezone\":{\"offset\":\"+03:00\",\"zoneabb\":\"EEST\",\"zoneoffset\":7200,\"zonedst\":3600,\"zonetotaloffset\":10800}},\"type\":[\"Season\"],\"locations\":\"All\",\"states\":\"All\"},\n" +
            "{\"name\":\"July Morning\",\"description\":\"July Morning is a observance in Bulgaria\",\"country\":{\"id\":\"bg\",\"name\":\"Bulgaria\"},\"date\":{\"iso\":\"2020-07-01\",\"datetime\":{\"year\":2020,\"month\":7,\"day\":1}},\"type\":[\"Observance\"],\"locations\":\"All\",\"states\":\"All\"}]}}";
}
